# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1908a07c725582ae804b179abb710567c4735383d3201721618d7ef5c1e5bb4ae71016e47b1c061a68f11f9ecd285f5feee9b70b06a1fd0d82e2f7bc8e552cb9

test:
  secret_key_base: e7d67ce1f692dbf1a78c0c258af90c7db3f12fe1da7a7d8abdb755a64936cba85a1e4652411fb7fe6a8b23ce54bc3b763f6c15c9eebabbb655f359b1c76ef2d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
